Greatly improve efficiency of IO
Earthcomputer/clientcommands pull request #230
Opened 2021-04-11 00:20 UTC by xpple

I wanted to do the IO this way earlier, but that wasn't possible as I was storing `PlayerInventory`s which couldn't be loaded without the player. Now that `ListTag`s are stored instead (as suggested by Earthcomputer 👍 ), this **is** possible. The file is only loaded once `onInitializeClient`, and will only be saved afterwards. If the file couldn't be read, the command is logically not registered.

2021-04-11 00:25 UTC, haykam821 commented
Why not load it the first time it is required?

2021-04-11 00:35 UTC, xpple commented
Funnily I also had that at one point, but I didn’t like having to set a Boolean to false in 5 methods just to delay the IO of one file

2021-04-11 00:36 UTC, xpple commented
More importantly, if you do it the first time it is required, the `suggest`ions won’t be available because the file and thus `Map` hasn’t been loaded

2021-04-11 00:37 UTC, xpple commented
> More importantly, if you do it the first time it is required, the `suggest`ions won’t be available because the file and thus `Map` hasn’t been loaded

This PR also fixes that issue

2021-04-11 12:37 UTC, Earthcomputer requested changes
I don't like calling this directly inside `ClientCommands`, it breaks encapsulation. Probably best inside a `static {}` block.

2021-04-11 12:54 UTC, xpple commented
I thought it’d make sense to have it here, because it’s where all the commands are registered. Similar to the one which is being registered based on an `if`, this one is registered based on the fact that the IO worked or not

2021-04-11 13:56 UTC, Earthcomputer commented
Why would the I/O not work? That's an error case, not a simple if "either-could-happen" case. Just log something to the console to be honest.

2021-04-11 14:05 UTC, xpple commented
Honestly no idea how the IO would not work, but then again, it’s an _exception_! And I _am_ logging something to the console if it doesn’t work. I extracted the error handling to the `ClientCommands` class, because depending on the success of the IO, the command will be registered (or not). If the IO didn’t work the entire command is useless, and also useless to have registered.

2021-04-12 10:11 UTC, Earthcomputer requested changes

2021-04-12 10:11 UTC, Earthcomputer commented on src/main/java/net/earthcomputer/clientcommands/command/KitCommand.java
> +            final Logger logger = LogManager.getLogger();
Loggers should be a private static final field at the top of the class, and should specify the name "clientcommands".

2021-04-12 10:11 UTC, Earthcomputer commented on src/main/java/net/earthcomputer/clientcommands/command/KitCommand.java
> +            logger.info(I18n.translate("commands.ckit.loadFile.failed"));
Log messages don't need to be translated.

2021-04-12 18:07 UTC, Earthcomputer approved these changes
Lgtm

2021-04-12 18:07 UTC, merged