[DO NOT MERGE YET] Updated Simplified Chinese translation
Earthcomputer/clientcommands pull request #283
Opened 2021-06-20 06:35 UTC by user670

**Do not merge until I say otherwise!** This edit is not complete; there are a few things that I am unsure of.

- Fishing: what correction? what "ticks ahead"?
- item group? kit? (For now I translated "item group" literally; "kit" as "preset inventory" as described in the change log that added that command)
- "Stopped sound '%s' on source '%s' for self", Chinese seems to have a different word order for the two %s. Can they swap positions somehow, or do I have to rephrase to keep the order? (also, what source?)

2021-06-20 17:42 UTC, haykam821 commented
You can open your pull request as a draft if it is not ready to be merged yet.

2021-06-20 18:12 UTC, sjx233 requested changes

2021-06-20 18:12 UTC, sjx233 commented on src/main/resources/assets/clientcommands/lang/zh_cn.json
> +  "commands.citemgroup.setStack.success": "成功从 \"%s\" 将下表为 %d 的道具更改为 %s",
```suggestion
  "commands.citemgroup.setStack.success": "成功从 \"%s\" 将下标为 %d 的道具更改为 %s",
```

2021-06-20 18:12 UTC, sjx233 commented on src/main/resources/assets/clientcommands/lang/zh_cn.json
> +  "commands.cstopsound.success.source.sound": "为自己停止了来自 '%s$2' 的 '%s$1' 声音",
```suggestion
  "commands.cstopsound.success.source.sound": "为自己停止了来自 '%2$s' 的 '%1$s' 声音",
```

2021-06-21 06:21 UTC, sjx233 approved these changes

2021-06-21 06:26 UTC, user670 commented
Can I get some info on the questions I asked? Especially does the `%2$s` thing work?

2021-06-21 16:07 UTC, Earthcomputer commented
- For rng fishing, the correction is the amount of milliseconds earlier the packet is sent to cancel out delay caused by high ping. "Ticks ahead" is how many ticks away from tick the fishing rod should have been pulled in, which roughly represents the correction the client needs to apply for next time.
- Item group is like a creative tab in the creative menu. A kit is like a preset inventory, yes.
- Yes, `%2$s` works, that's how you change the word order from English.

2021-09-13 17:50 UTC, Neubulae commented on src/main/resources/assets/clientcommands/lang/zh_cn.json
> +  "commands.cfish.error.outOfWater": "钓鱼竿附表不在水中， 随机数操控无法工作",
“浮标”，a typo

2021-12-17 22:53 UTC, closed without merging

2021-12-18 00:16 UTC, Earthcomputer commented
Why close the PR?

2021-12-18 00:30 UTC, user670 commented
> Why close the PR?

It's probably outdated, and I don't plan to work on it any more. If I want to keep working on it, I'll work on the fresh thing in the repo, not this.

2021-12-18 17:06 UTC, Neubulae commented
lemme take a look and see what I can do with translation then, I'll do it when I have time