Add the ctitle command
Earthcomputer/clientcommands pull request #310
Opened 2021-08-13 01:37 UTC by haykam821

Fixes #282

2021-08-13 09:10 UTC, xpple commented
Please note that this was not intended to be in clientcommands, but rather intended as a script. I’m referring to [this message](https://discord.com/channels/703363189081112647/703598704266969099/865709229137199115).

2021-08-16 11:34 UTC, Earthcomputer commented
Eh whatever, it's not much work for me

2021-08-16 11:35 UTC, Earthcomputer requested changes

2021-08-16 11:35 UTC, Earthcomputer commented on src/main/java/net/earthcomputer/clientcommands/command/CTitleCommand.java
> +    private static final MinecraftClient CLIENT = MinecraftClient.getInstance();
The `MinecraftClient` is not immutable, all caps is for immutable objects

2021-08-16 11:35 UTC, Earthcomputer commented on src/main/java/net/earthcomputer/clientcommands/command/CTitleCommand.java
> +        return 1;
return 0

2022-04-03 17:19 UTC, Earthcomputer commented
This PR needs updating after the fcapi merge

2022-06-10 22:24 UTC, Earthcomputer approved these changes

2022-06-11 01:22 UTC, merged