Add /cping command
Earthcomputer/clientcommands pull request #385
Opened 2022-04-04 02:32 UTC by ImUrX

Just makes public the ping method from the ``FishingCracker`` and adds a ``/cping`` command

2022-04-04 10:56 UTC, Earthcomputer requested changes

2022-04-04 10:56 UTC, Earthcomputer commented on src/main/resources/assets/clientcommands/lang/en_us.json
> +  "commands.client.ping.multiplayer": "Your average ping is %dms",
Usually for commands we have `commands.cping`

2022-04-04 11:59 UTC, xpple requested changes
Some small [style guideline](https://github.com/Earthcomputer/clientcommands/blob/fabric/CONTRIBUTING.md#code-style) changes.

2022-04-04 11:59 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/PingCommand.java
> +import static net.fabricmc.fabric.api.client.command.v1.ClientCommandManager.literal;
`import static`s should always use wildcard imports.

2022-04-04 11:59 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/PingCommand.java
> +        if(ping == -1 || instance.isInSingleplayer()) {
There should be a space between the keyword and the statement-bracket.

2022-04-05 08:39 UTC, 5HT2 commented on src/main/java/net/earthcomputer/clientcommands/command/PingCommand.java
> +        int ping = FishingCracker.getLocalPing();
For what it's worth, it would make sense to move `getLocalPing` here and use `PingCommand.getLocalPing()` in `FishingCracker`.

2022-04-05 21:10 UTC, 5HT2 approved these changes

2022-04-06 10:51 UTC, Earthcomputer approved these changes

2022-04-06 10:51 UTC, merged