whisper using player's mojang provided public key to encrypt
Earthcomputer/clientcommands pull request #429
Opened 2022-06-24 19:40 UTC by wagyourtail

this is bad xd

2022-06-25 22:03 UTC, xpple requested changes
Overall really cool command, just a few code style suggestions.

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +public class WhisperEncrypted {
Could you add the `Command` suffix to this class?

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +import static net.minecraft.command.CommandSource.suggestMatching;
`import static`s should use wildcard imports.

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +        dispatcher.register(literal("cwhisperencrypted")
I think this root literal is rather long, what about `/cwe`?

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +                .then(argument("player", string())
You can use the `CGameProfileArgumentType`.

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +        String player = context.getArgument("player", String.class);
It's usual to add the `FabricClientCommandSource` and the command parameters as parameters to the method. You can also use the `FabricClientCommandSource` to access the `MinecraftClient` instance.

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +            return 0;
It's usual to throw en exception when the command fails somehow.

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +                return 0;
Same as above.

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +                return 0;
Same as above.

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +                return 0;
Same as above.

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +            context.getSource().sendError(Text.translatable("commands.cplayerinfo.ioException"));
Same as above and perhaps you could create a custom error message for this command.

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +        return 1;
Return `Command.SINGLE_SUCCESS` instead.

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +            } catch ( Exception e) {
```suggestion
            } catch (Exception e) {
```

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +                    if (codePoint >= UPPER_BOUND) throw new RuntimeException("WHAT?");
Every `if`-statement should have curly brackets.

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +                if (codePoint >= UPPER_BOUND) throw new RuntimeException("WHAT?");
Same as above.

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +                if (codepoint >= UPPER_BOUND) throw new RuntimeException("WHAT?");
Same as above.

2022-06-25 22:03 UTC, xpple commented on src/main/resources/assets/clientcommands/lang/en_us.json
> +  "commands.cwhisperencrypted.pub_key_not_found": "Public key not found",
This doesn't match the convention of using camelCase for translation keys.

2022-06-25 22:03 UTC, xpple commented on src/main/resources/assets/clientcommands/lang/en_us.json
> +
```suggestion
```

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +            for (int i = 0; i < s.length(); ) {
```suggestion
            for (int i = 0; i < s.length();) {
```

2022-06-25 22:03 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncrypted.java
> +                            "commands.cplayerinfo.ioException").formatted(Formatting.DARK_RED));
Same as above, regarding the custom error message.

2022-06-26 16:31 UTC, xpple requested changes

2022-06-26 16:31 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncryptedCommand.java
> +                    .then(argument("message", gameProfile())
```suggestion
                .then(argument("player", gameProfile())
                    .then(argument("message", string())
```

2022-06-26 16:31 UTC, xpple commented on src/main/java/net/earthcomputer/clientcommands/command/WhisperEncryptedCommand.java
> +                            )
```suggestion
                            whisper(ctx.getSource(),
                                CGameProfileArgumentType.getCProfileArgument(ctx, "player"),
                                getString(ctx, "message")
                            )
```

2022-11-01 19:22 UTC, xpple approved these changes

2022-11-19 18:09 UTC, Earthcomputer commented
Superseded by #461

2022-11-19 18:09 UTC, closed without merging