Add #612
Earthcomputer/clientcommands pull request #637
Opened 2024-05-27 01:49 UTC by RealRTTV

2024-05-28 02:58 UTC, RealRTTV commented
lgtm

2024-05-28 20:58 UTC, Earthcomputer requested changes

2024-05-28 20:58 UTC, Earthcomputer commented on src/main/java/net/earthcomputer/clientcommands/features/EnchantmentCracker.java
> +                                    builder.append(Component.literal("~" + Math.round(100.0 * current / total) + "%").withColor(color));
You might want to cast the `Math.round` back to an `int` just so you don't get the `.0` in the string.

2024-05-28 20:58 UTC, Earthcomputer commented on src/main/java/net/earthcomputer/clientcommands/features/EnchantmentCracker.java
> +                                    int unfilled_width = PROGRESS_BAR_WIDTH - filled_width;
Please use camel case for variables

2024-05-28 20:59 UTC, RealRTTV commented on src/main/java/net/earthcomputer/clientcommands/features/EnchantmentCracker.java
> +                                    int unfilled_width = PROGRESS_BAR_WIDTH - filled_width;
again, sorry, idk why i did this

2024-05-29 00:11 UTC, Earthcomputer approved these changes

2024-05-29 00:12 UTC, merged