Fix recursive alias detection
Earthcomputer/clientcommands pull request #649
Opened 2024-06-23 17:00 UTC by mygizli04

Fixes #645 

When trying to detect whether or not an alias is recursive, it's added to an array of seen aliases. However this array was never cleared meaning after an alias is executed, it cannot be executed again with the error 'Recursive alias "[name of alias]"' appearing in chat despite there being no recursion.

I've confirmed that this issue does not occur on 2.8.18 but occurs after 2.8.19, after the recursion detection was added.

This pull request fixes the issue by removing the alias from the list of seen aliases after the command is completed.

2024-06-23 17:41 UTC, Earthcomputer requested changes
You can use [try-finally](https://docs.oracle.com/javase%2Ftutorial%2F/essential/exceptions/finally.html) in Java to make this a bit cleaner

2024-06-24 00:42 UTC, mygizli04 commented
Thanks for taking the time to respond, I'm not sure if I understood exactly what you mean but I wrapped the entire function in a try-finally block. If that's not what you meant please let me know.

2024-06-24 08:39 UTC, Earthcomputer commented
This is almost good, although the try-finally should start after the addition of the alias key to the set.

2024-06-24 14:43 UTC, mygizli04 commented
Alright, how about now?

2024-06-24 14:51 UTC, Earthcomputer requested changes
One more thing and we're good to go.

2024-06-24 14:51 UTC, Earthcomputer commented on src/main/java/net/earthcomputer/clientcommands/command/AliasCommand.java
> +
Can you remove this extra indentation?

2024-06-24 15:53 UTC, mygizli04 commented on src/main/java/net/earthcomputer/clientcommands/command/AliasCommand.java
> +
Ah, my bad. Fixed now.

2024-06-24 16:07 UTC, Earthcomputer approved these changes

2024-06-24 16:10 UTC, merged