Added a way to limit xp used with /cenchant
Earthcomputer/clientcommands pull request #667
Opened 2024-10-24 21:18 UTC by Starmania

This is useful when you want to use as little xp level as possible.

How did I tested this pr:

```log
[23:05:15] [Render thread/INFO]: [CHAT] Player RNG cracked: c1700935c5bb

[23:05:17] [Render thread/INFO]: [CHAT] maxExperienceConsumed has been set to 1.

[23:05:23] [Render thread/INFO]: [CHAT] Starting enchantment manipulation. Cancel
[23:05:23] [Render thread/INFO]: [CHAT] Item throws needed: 8 (about 0.4 seconds)
[23:05:23] [Render thread/INFO]: [CHAT] Bookshelves needed: 5
[23:05:23] [Render thread/INFO]: [CHAT] In slot: 1
[23:05:23] [Render thread/INFO]: [CHAT] Enchantments on item:
[23:05:23] [Render thread/INFO]: [CHAT] - Aqua Affinity

[23:05:24] [Render thread/INFO]: [CHAT] maxExperienceConsumed has been set to 3.

[23:05:27] [Render thread/INFO]: [CHAT] Starting enchantment manipulation. Cancel
[23:05:27] [Render thread/INFO]: [CHAT] Item throws needed: 5 (about 0.25 seconds)
[23:05:27] [Render thread/INFO]: [CHAT] Bookshelves needed: 13
[23:05:27] [Render thread/INFO]: [CHAT] In slot: 3
[23:05:27] [Render thread/INFO]: [CHAT] Enchantments on item:
[23:05:27] [Render thread/INFO]: [CHAT] - Power III
[23:05:27] [Render thread/INFO]: [CHAT] - Aqua Affinity
```

I can rename the config option to `getMaxExperienceLevelConsumed` or something like that but it's becoming pretty long. As you want.

2024-10-24 21:21 UTC, Earthcomputer commented
This is the same as which slot to use, so could it be renamed to `maxEnchantSlot` or something? I think that's clearer

2024-10-25 08:27 UTC, Starmania commented
Yeah, why not... Naming variables is the most difficult thing to do.

2024-11-26 19:30 UTC, Earthcomputer requested changes
Waiting on the config option to be renamed

2025-02-19 23:12 UTC, Earthcomputer approved these changes

2025-02-19 23:12 UTC, merged